access_key = "AKIAIFRMFM7HEQANY7EA"
secret_key = "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"
ec2_key_pair_name = "spark-key-pair"
ec2_secret_key_file_path = "/home/joe/Downloads/spark-key-pair.pem"
spark_rsa_private_key_file_path = "/home/joe/.ssh/id_rsa"
spark_rsa_public_key_file_path = "/home/joe/.ssh/id_rsa.pub"